### ISSUE TITLE
api管理后台404错误

### ISSUE THREAD

**Issue by coolayou** [lejianwen/rustdesk-api#1]
通过如下配置安装了  登陆 http://xxx::21114  或者http://xxxx:21114/admin   提示404错误 在软件里面使用 admin admin 到是可以登陆 就是没法访问网页后台
version: '3'

networks:
  rustdesk-net:
    external: false
services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116 # 自定义 hbbs 映射端口
      - 21116:21116/udp # 自定义 hbbs 映射端口
      - 21118:21118 # web client 需要
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r xxxx:21117 -k xxx# 填入个人域名或 IP + hbbr 暴露端口
    volumes:
       - /share/Container/Docker/hbbs:/root # 自定义挂载目录
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117 # 自定义 hbbr 映射端口
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k xxx
    #command: hbbr
    volumes:
      - /share/Container/Docker/hbbr:/root # 自定义挂载目录
    networks:
      - rustdesk-net
    restart: unless-stopped

  rustdesk-api:
    container_name: rustdesk-api
    ports:
      - 21114:21114
    image: lejianwen/rustdesk-api:latest
    volumes:
      - /share/Container/Docker/rdpapi:/app/data #将数据库挂载出来方便备份
    networks:
      - rustdesk-net
    restart: unless-stopped

**Comment by lejianwen** [comment]
是访问http://xxxx:21114/_admin/
有个下划线
