### ISSUE TITLE
设备管理功能及API问题

### ISSUE THREAD

**Issue by yczhl21** [lejianwen/rustdesk-api#10]
感谢作者，太好的开源
1、如果设备管理能加上 搜索框，可检索 ID或主机名 模拟查询就好了
2、WEB-client 能在在参数配置两种模式就好，
一种是WEB，另一种是URI 如：rustdesk://ID'启动客户端
3、怎样不收藏 的情况下能搜索所有设备
4、还有，API不太懂得用，怎么get请求到相关数据

**Comment by lejianwen** [comment]
1.可以的，我后面加上
2.这个我尝试过，但客户端并没有注册url protocol，所以无法做到
3.不太明白你的意思
4.你是说swagger文档获取不到数据吗？具体是什么样的问题呢

**Comment by lejianwen** [comment]
关于2，我之前客户端是非安装模式，我测试了安装模式，是有url protocol的，我后面加上

**Comment by yczhl21** [comment]
感谢作者这么及时的回复关注，本人也是远程重度用户，浏览太多相关开源，感谢作者这款非常强大、适用、简洁
关于上面分组、测试中有两个用户，都在共享组，在PC端，都试过，小组里没有显示，不知道我理解是否正确，道理上应该是在共享组里管理员能看所有组内人员的地址薄，但现实看不见。
关于问题三，希望增一个组，只要加入此组中，都可见所有设备并搜索，因为有新设备进入后需要人工增加到收藏 才可见，如果有这个组，那么所有新加入设备都有权限查看使用，不用一个个收藏到地址薄，可在客户端随时可查；
另外设备管理，需要下拉到底部才让横拉条可见，这个操作不太好，应该列表内容在一个活动窗口，操作、页数等应该固定
关于API，可能我没有看懂，主要是想借用这个功能，快速定位 到ID并调用，比如通过主机信息匹配到ID并使用，能否给一个示例

**Comment by lejianwen** [comment]
共享组是所有成员都能看见，就是透明的，普通组只有管理员可看见其他人
PC端群组那里显示的是机器信息，不是成员的地址簿。如果成员在该机器上登录了，这个机器会绑定到这个用户，这个我也只是根据官方的数据结构和接口来猜的，最开始的版本是显示地址簿，但感觉不对，而且个人版的API其实是有共享功能，我还没支持到，也不知道怎么做比较符合逻辑。
用户是属于组，组有组名和组类型，必须组类型是共享组才能都看到
`设备管理，需要下拉到底部才让横拉条可见` 这个是什么意思？ 是在移动设备上使用的后台吗？
`关于API，可能我没有看懂，主要是想借用这个功能，快速定位 到ID并调用，比如通过主机信息匹配到ID并使用，能否给一个示例`这个我不太明白什么意思
现在更新到v2.3.1了 你可以试试
设备管理可以按ID和主机名搜索了
通过url protocol启动也加上了

**Comment by 1350962574** [comment]
> 1.可以的，我后面加上 2.这个我尝试过，但客户端并没有注册url protocol，所以无法做到 3.不太明白你的意思 4.你是说swagger文档获取不到数据吗？具体是什么样的问题呢

同样非常感谢作者这么棒的项目，但是我有个建议或者是提议，不知道是否可以实现
能否做到权限控制，就是非管理员对地址薄可读不可写，以防删库跑路！！！

**Comment by lejianwen** [comment]
> > 1.可以的，我后面加上 2.这个我尝试过，但客户端并没有注册url protocol，所以无法做到 3.不太明白你的意思 4.你是说swagger文档获取不到数据吗？具体是什么样的问题呢
> 
> 同样非常感谢作者这么棒的项目，但是我有个建议或者是提议，不知道是否可以实现 能否做到权限控制，就是非管理员对地址薄可读不可写，以防删库跑路！！！

额，地址簿删了没事啊，设备还在的，地址簿其实是基于设备

**Comment by yczhl21** [comment]
非常感谢作者关注，作为使用者，也希望产品更好用，再提几个问题
1、地址薄、设备管理列表等的列，增加自定义显示功能，比如Hash、UUID等过长，如果能自定义隐藏列，显示效果更好
2、还是那个功能就是用户加到特定组后，我暂且命令为全局组，如果加入到此组，在客户端程序登录后，能在小组中查看或搜索到所有设备信息
3、想通过搭建的API，通过GET请求，比如 http://192.168.1.7/api？hostname=pcname 通过参数方式获取 到返回信息，比如参数为主机名，返回该ID相关json信息，
看了说明有这个 <youer server[:port]>/swagger/index.html ，测试很多次，可能 我还是没懂如何使用，是否是我理解 的不一样
，其实我的主要目的是，在知道对方PC名称hostname的情况下自动获取 到该设备的id相关信息，可直接脚本方式调用启动远程客户端如
C:\Program Files\RustDesk\rustdesk.exe --connect {rustdeskid}
4、另一个问题，对于经常登录后台，不想次次输密码，是否可以加参数自动登录

**Comment by Salem-Su** [comment]
好奇的问一下，我用postman执行http:/xxxxxxxxx:21114/api/admin/peer/list提示我需要登录，但我同样的在http://xxxxxxxxx:21114/api/admin/login登录了并且拿到了token,不确认是不是我的方法有问题

**Comment by lejianwen** [comment]
token 要放入到header中`Authorization: Bearer <token>`

**Comment by Salem-Su** [comment]
> token 要放入到header中`Authorization: Bearer <token>`

肯定是放了的

**Comment by lejianwen** [comment]
你把postman的请求copy成curl发一下看看，ip模糊处理下

**Comment by Salem-Su** [comment]
这是登录:
curl --location --request POST 'http://xxxxx:21114/api/admin/login' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "password": "xxxxx",
  "platform": "test",
  "username": "admin"
}'

这是getlist
curl --location --request GET 'http://xxxxx:21114/api/admin/peer/list' \
--header 'Authorization: Bearer 89df63f49777110ceebf134cce1dc1db' \
--data-raw ''

**Comment by lejianwen** [comment]
admin那边是`api-token: xxx`

**Comment by Salem-Su** [comment]
谢谢，可以了

**Comment by yczhl21** [comment]
> 谢谢，可以了

admin那边是api-token: xxx 
这个加在哪个位置，能否给一个示例，谢谢

**Comment by lejianwen** [comment]
> > 谢谢，可以了
> 
> admin那边是api-token: xxx 这个加在哪个位置，能否给一个示例，谢谢

就是放在`Header`里面就可以了

**Comment by yczhl21** [comment]
谢谢，可以了
