### ISSUE TITLE
客户端内添加ID无法获取到 username,hostname,platform

### ISSUE THREAD

**Issue by 1350962574** [lejianwen/rustdesk-api#13]
客户端内添加新的 ID 到地址薄时无法自动补全 `username hostname platform` 等信息
客户端注册为服务后貌似会定时将这些信息传入到接口
Tips：作者可以在自述文件中放置打赏渠道吗？！这么棒的项目应该得到支持。

![图像2024-10-15 21 49](https://github.com/user-attachments/assets/01b5abad-6004-477d-9c2f-77a88221da41)

**Comment by 1350962574** [comment]
![Uploading 图像2024-10-15 21.48.jpeg…]()

**Comment by lejianwen** [comment]
已修复， 你试试

**Comment by 1350962574** [comment]
> 已修复， 你试试
貌似不行！！！

**Comment by lejianwen** [comment]
设备里面有这个ID了吗？如果没有的话也会获取不到的

**Comment by 1350962574** [comment]
设备中有这个 ID

**Comment by lejianwen** [comment]
你的客户端版本是多少呢？

**Comment by 1350962574** [comment]
主控1.3.1
被控1.3.2

**Comment by lejianwen** [comment]
你先删除地址簿这个地址，再次添加ID试试？
你下面有这个标签吗？
![image](https://github.com/user-attachments/assets/f4e28ce6-2846-496f-ba6f-48edeb5a1f64)

**Comment by 1350962574** [comment]
是的 我尝试的操作就是删除地址薄中设备(ID)并再次添加
没有发现小云朵，需要我配置为个人版么

**Comment by lejianwen** [comment]
最好是开启个人版，个人版的接口更精确
非个人版这个地方就是一整坨数据传来传去

**Comment by lejianwen** [comment]
我再修复下非个人版的

**Comment by 1350962574** [comment]
切换到个人版，就可以了！！！

**Comment by lejianwen** [comment]
我刚测试了下非个人版，添加后，还是个空的，还必须点刷新图标，刷新一下才可以

**Comment by lejianwen** [comment]
已经推上去了，等构建完应该就可以了

**Comment by 1350962574** [comment]
好的 Perfect！！！

**Comment by lejianwen** [comment]
构建完了，你试试

**Comment by 1350962574** [comment]
可以了！！！

**Comment by lejianwen** [comment]
ok
