### ISSUE TITLE
没搞懂为啥要不停写数据库，有没有试过300+客户端？

### ISSUE THREAD

**Issue by zhangbo8418** [lejianwen/rustdesk-api#14]
我这边被人白嫖了，300+客户端，心跳包不停写数据库每秒10M+的持续写入。。。上次我将心跳存内存，只有后台查看设备时才会写入，但是这次更新又有数据不停写数据库。。。
![QQ图片20241016202712](https://github.com/user-attachments/assets/df8f7ff6-0575-431e-be2f-125dde6824f2)

**Comment by lejianwen** [comment]
更新了一版 你试试，应该能缓解很多

**Comment by zhangbo8418** [comment]
> 更新了一版 你试试，应该能缓解很多

明天测试了，这个我上次就修改过，只是这次应该不是这边的心跳，我上次都没让它写数据库，修改如下

package api

import (
	requstform "Gwen/http/request/api"
	"Gwen/http/response"
	"Gwen/service"
	"Gwen/model"
	"github.com/gin-gonic/gin"
	"net/http"
	"sync"
	"time"
)

type Index struct {
}

// 缓存变量
var peerCache sync.Map

// Index 首页
// @Tags 首页
// @Summary 首页
// @Description 首页
// @Accept  json
// @Produce  json
// @Success 200 {object} response.Response
// @Failure 500 {object} response.Response
// @Router / [get]
func (i *Index) Index(c *gin.Context) {
	response.Success(
		c,
		"Hello Gwen",
	)
}

// UpdateCacheToDB 遍历缓存并将数据更新到数据库
func UpdateCacheToDB() {
	peerCache.Range(func(key, value interface{}) bool {
		peer := value.(*model.Peer)  // 从缓存中取出 model.Peer
		service.AllService.PeerService.Update(peer)  // 更新到数据库
		peerCache.Delete(key)  // 更新后从缓存中删除
		return true
	})
}

// Heartbeat 心跳
// @Tags 首页
// @Summary 心跳
// @Description 心跳
// @Accept  json
// @Produce  json
// @Success 200 {object} nil
// @Failure 500 {object} response.Response
// @Router /heartbeat [post]
func (i *Index) Heartbeat(c *gin.Context) {
	info := &requstform.PeerInfoInHeartbeat{}
	err := c.ShouldBindJSON(info)
	if err != nil {
		c.JSON(http.StatusOK, gin.H{})
		return
	}
	if info.Uuid == "" {
		c.JSON(http.StatusOK, gin.H{})
		return
	}
	// 先从缓存中查找对应的 `peer` 数据
	peerInterface, ok := peerCache.Load(info.Uuid)
	var peer *model.Peer
	// 如果缓存中不存在数据，从数据库中查找
	if !ok {
		peer = service.AllService.PeerService.FindByUuid(info.Uuid)
		if peer == nil {
			// 如果数据库中也找不到，返回空响应
			c.JSON(http.StatusOK, gin.H{})
			return
		}
	} else {
		// 如果缓存中存在数据，转换类型
		peer = peerInterface.(*model.Peer)
	}
	peer.LastOnlineTime = time.Now().Unix()
	// 将更新后的数据重新存入缓存
	peerCache.Store(info.Uuid, peer)
	c.JSON(http.StatusOK, gin.H{})
}

然后在
package admin

import (
	"Gwen/global"
	"Gwen/http/request/admin"
	"Gwen/http/response"
	"Gwen/http/controller/api"
	"Gwen/service"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
	"strconv"
	"time"
)

// List 列表
// @Tags 设备
// @Summary 设备列表
// @Description 设备列表
// @Accept  json
// @Produce  json
// @Param page query int false "页码"
// @Param page_size query int false "页大小"
// @Param time_ago query int false "时间"
// @Param id query string false "ID"
// @Param hostname query string false "主机名"
// @Success 200 {object} response.Response{data=model.PeerList}
// @Failure 500 {object} response.Response
// @Router /admin/peer/list [get]
// @Security token
func (ct *Peer) List(c *gin.Context) {
	// 缓存更新到数据库
	api.UpdateCacheToDB()
	
	query := &admin.PeerQuery{}
	if err := c.ShouldBindQuery(query); err != nil {
		response.Fail(c, 101, response.TranslateMsg(c, "ParamsError")+err.Error())
		return
	}
	res := service.AllService.PeerService.List(query.Page, query.PageSize, func(tx *gorm.DB) {
		if query.TimeAgo > 0 {
			lt := time.Now().Unix() - int64(query.TimeAgo)
			tx.Where("last_online_time < ?", lt)
		}
		if query.TimeAgo < 0 {
			lt := time.Now().Unix() + int64(query.TimeAgo)
			tx.Where("last_online_time > ?", lt)
		}
		if query.Id != "" {
			tx.Where("id like ?", "%"+query.Id+"%")
		}
		if query.Hostname != "" {
			tx.Where("hostname like ?", "%"+query.Hostname+"%")
		}
	})
	response.Success(c, res)
}


这次我没有研究问题出在哪里。。。。

**Comment by lejianwen** [comment]
如果不是心跳接口，那最近更新的就是日志写入，登录失败会写入日志。你可以看下日志
还有SysInfo接口，会更新设备，但这个接口调用量更小，应该不会

**Comment by zhangbo8418** [comment]
> 如果不是心跳接口，那最近更新的就是日志写入，登录失败会写入日志。你可以看下日志 还有SysInfo接口，会更新设备，但这个接口调用量更小，应该不会

我都躺床上了，不想动😂，不过日志会写数据库么？我的数据库每2秒更新一次

**Comment by lejianwen** [comment]
嗯，明天再看吧，日志不写数据库的，之前心跳确实没想那么多，就是更新了在线时间，Pc客户端是15秒一次心跳，你设备多的话确实会有这种问题
大户人家啊~~~~

**Comment by lejianwen** [comment]
日志是写文件

**Comment by zhangbo8418** [comment]
> 嗯，明天再看吧，日志不写数据库的，之前心跳确实没想那么多，就是更新了在线时间，Pc客户端是15秒一次心跳，你设备多的话确实会有这种问题 大户人家啊~~~~

其实我也不想的，这个客户端如果不修改就会导致登陆账号后同时使用key会导致连不上，我当时修改客户端给别人用，我是让他们自己搭建，谁知道他们直接白嫖我的。。。现在我是改服务端，客户端不用改了，但是已经晚了。。。

**Comment by lejianwen** [comment]
额，你把暴露端口改了就可以防止白嫖了吧

**Comment by 1350962574** [comment]
> 我这边被人白嫖了，300+客户端，心跳包不停写数据库每秒10M+的持续写入。。。上次我将心跳存内存，只有后台查看设备时才会写入，但是这次更新又有数据不停写数据库。。。 ![QQ图片20241016202712](https://private-user-images.githubusercontent.com/46797568/377050365-df8f7ff6-0575-431e-be2f-125dde6824f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTEzMTAsIm5iZiI6MTcyOTA5MTAxMCwicGF0aCI6Ii80Njc5NzU2OC8zNzcwNTAzNjUtZGY4ZjdmZjYtMDU3NS00MzFlLWJlMmYtMTI1ZGRlNjgyNGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE1MDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTU2M2Y4MzM1Y2VmNjE5ZDM3ZmM4MTEyMGJmODFlMmRiNjU3NGMzNmQ2NzcxMDI0ZmI2MmRiMTljMTIxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JX3PL1J8AiR55bNXvbs0TnueuDElDGmkLTTaIJQK1nU)

hbbs,hbbr被白嫖？？如果是的话可以加入key检验，或者使用另外一个(非官方)server项目可以阻止非登录设备发起远控
![7fb3900189d935ba6e60685868440d69](https://github.com/user-attachments/assets/08faed26-3649-4265-b988-6f8ed44829f2)

**Comment by zhangbo8418** [comment]
> 日志是写文件

} else {
	if pe.UserId == 0 {
		pe.UserId = service.AllService.UserService.FindLatestUserIdFromLoginLogByUuid(pe.Uuid)
	}
	fpe.RowId = pe.RowId
	fpe.UserId = pe.UserId
	err = service.AllService.PeerService.Update(fpe)
	if err != nil {
		response.Error(c, response.TranslateMsg(c, "OperationFailed")+err.Error())
		return
	}
}


应该是这段吧？？如果没有登陆是不是pe.UserId == 0？？？

**Comment by zhangbo8418** [comment]
如果pe.UserId是0的话，多个未登陆用户有不同的pe.Uuid可能就导致了不停更新

**Comment by lejianwen** [comment]
`pe.UserId == 0`只是判断是否绑定了用户，为了绑定一下所属用户的，SysInfo接口调用频率很低，返回空字符串的话是大概`2分钟/次`应该不是这个问题，
建议你看看日志,在`runtime/log.txt`，看是不是有人暴力登录

**Comment by zhangbo8418** [comment]
> `pe.UserId == 0`只是判断是否绑定了用户，为了绑定一下所属用户的，SysInfo接口调用频率很低，返回空字符串的话是大概`2分钟/次`应该不是这个问题， 建议你看看日志,在`runtime/log.txt`，看是不是有人暴力登录

就是，我滚回上一版的代码，只有创建没有更新就没有频繁写入了。。。这个接口是登陆才会调用还是什么？或者是不是要做个判断，判断数据是否有变化，如果没有变化就不更新？

**Comment by lejianwen** [comment]
那就返回SYSINFO_UPDATED应该就不会这样了

**Comment by lejianwen** [comment]
我提交了，你试试

**Comment by zhangbo8418** [comment]
> 我提交了，你试试

![QQ截图20241017112829](https://github.com/user-attachments/assets/0232eed0-ded4-44e6-aa9e-864ab3615d52)

没变化，这个更新本身就写入数据量不大

**Comment by zhangbo8418** [comment]
> 我提交了，你试试

不对，有变化，只是刚启动几分钟有持续写入，现在没有了
![QQ截图20241017113343](https://github.com/user-attachments/assets/c811454c-f8b2-4fbe-a0f1-809933280d77)

**Comment by lejianwen** [comment]
OK，那就好，看来这几个返回参数还是有用的
