### ISSUE TITLE
修改了secure_tcp的fork版本在macos上无法运行

### ISSUE THREAD

**Issue by Ogannesson** [lejianwen/rustdesk-api#15]
我尝试了您fork后修改了secure_tcp的版本，在Windows和Android上运行良好，但在macos上运行不正常。
我的设备为m1 macbook air。系统版本为macos15.1。下载的二进制文件版本为rustdesk-1.3.2-aarch64-aarch64.dmg
即使我以管理员身份忽略不安全警告，点击运行依然没有反应，活动监视器中也没有看到相关进程，由于您fork的仓库没开issue，我在此处提出问题。

**Comment by zhangbo8418** [comment]
> 我尝试了您fork后修改了secure_tcp的版本，在Windows和Android上运行良好，但在macos上运行不正常。 我的设备为m1 macbook air。系统版本为macos15.1。下载的二进制文件版本为rustdesk-1.3.2-aarch64-aarch64.dmg 即使我以管理员身份忽略不安全警告，点击运行依然没有反应，活动监视器中也没有看到相关进程，由于您fork的仓库没开issue，我在此处提出问题。

你得签名啊。。。。

**Comment by lejianwen** [comment]
你好，实在抱歉，我没有Mac系统。。。对mac os也不很了解
实在是抱歉

**Comment by lejianwen** [comment]
我搜索了一下 好像是要设置`安全性与隐私`

**Comment by Ogannesson** [comment]
> > 我尝试了您fork后修改了secure_tcp的版本，在Windows和Android上运行良好，但在macos上运行不正常。 我的设备为m1 macbook air。系统版本为macos15.1。下载的二进制文件版本为rustdesk-1.3.2-aarch64-aarch64.dmg 即使我以管理员身份忽略不安全警告，点击运行依然没有反应，活动监视器中也没有看到相关进程，由于您fork的仓库没开issue，我在此处提出问题。
> 
> 你得签名啊。。。。

我仔细排查了一下，确实是签名问题，我之前一直通过描述文件全局禁用了签名检查，但可能在近期的beta版本中失效了，我会尝试手动签名后能否运行。

**Comment by Ogannesson** [comment]
> 我搜索了一下 好像是要设置`安全性与隐私`

你好，经过排查，是我禁用签名检查的描述文件失效了，在我手动为程序签名后恢复正常了，是原仓库构建流程就存在的问题，与修改无关。
