### ISSUE TITLE
Google OAuth callback超时

### ISSUE THREAD

**Issue by Ogannesson** [lejianwen/rustdesk-api#16]
由于网络原因，使用Google登录时callback超时无法联通，是否存在为OAuth设置代理的选项？

**Comment by lejianwen** [comment]
没有这个选项，我到时候加一个

**Comment by Ogannesson** [comment]
> 没有这个选项，我到时候加一个

我下午自己改了一版，从环境变量读取HTTP_PROXY，我自己用起来没问题

**Comment by Ogannesson** [comment]
我将其提交到了[PR](https://github.com/lejianwen/rustdesk-api/pull/17)

**Comment by lejianwen** [comment]
好的，感谢，我合并一下，我想将环境变量加个RUSTDESK_API前缀可以吗？顺便配置文件也可以设置

**Comment by Ogannesson** [comment]
> 好的，感谢，我合并一下，我想将环境变量加个RUSTDESK_API前缀可以吗？顺便配置文件也可以设置

我又改了一下代码，换成了从config.go载入配置，现在应该可以同时支持配置文件和环境变量了，环境变量使用RUSTDESK_API_PROXY_ENABLE和RUSTDESK_API_PROXY_HOST

**Comment by lejianwen** [comment]
已合并，谢谢大佬
