### ISSUE TITLE
可以为arm64添加支持吗

### ISSUE THREAD

**Issue by rayangl** [lejianwen/rustdesk-api#2]
希望增加arm64的Docker

**Comment by lejianwen** [comment]
可以的，不过我身边没有arm64设备，无法很好的测试
我发布一个镜像lejianwen/rustdesk-api:test-arm64， 你可以帮我测试一下吗？
如果不行，可以下载release中的arm64二进制文件试试

**Comment by lejianwen** [comment]
release中的arm64 是在Ubuntu上编译的

**Comment by rayangl** [comment]
方便微信沟通吗，测试了几次，没有成功，我的硬件是radax e20c 使用的s6镜像`version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server-s6:latest
    environment:
      - "RELAY=rustdesk.example.com:21117"
      - "ENCRYPTED_ONLY=1"
    volumes:
      - ./data:/data
    restart: unless-stopped`
`version: "3.8"
services:
  rustdesk-api:
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.example.com:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.example.com:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://rustdesk.example.com:21114
      - RUSTDESK_API_RUSTDESK_KEY=#S6容器自动生成的key
    network_mode: host
    image: lejianwen/rustdesk-api:v2.0.1-arm64
    volumes:
      - /data/rustdesk/api:/app/data
    restart: unless-stopped`

然后使用`docker-compose -f /ext_overlay/docker/rustdesk-api-server/rustdesk-api-server.yml up -d`提示出错，
![image](https://github.com/user-attachments/assets/ad90c237-a673-4634-9f0e-84fabf6c42a7)
![image](https://github.com/user-attachments/assets/8e65284e-85f8-4dea-b592-33483607003e)

**Comment by rayangl** [comment]
![image](https://github.com/user-attachments/assets/4d226d1f-b96f-4407-9df8-2c67f587600c)

**Comment by lejianwen** [comment]
是我的问题，我镜像打包解压错位置了，
你使用 **lejianwen/rustdesk-api:v2.1.0-arm64** 再试试

**Comment by lejianwen** [comment]
有时间的话，可以帮我测试下**lejianwen/rustdesk-api:test-arm64**吗？
我看你使用了s6镜像，会需要有点改动才能使用
https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#docker%E8%BF%90%E8%A1%8C
![image](https://github.com/user-attachments/assets/97394112-481e-4b06-a31c-67eb9a1a4d84)

**Comment by rayangl** [comment]
2.1.0可以启动了，我就是没看懂这两个启动脚本怎么用

**Comment by rayangl** [comment]
![image](https://github.com/user-attachments/assets/f9d3e2af-751d-4572-a93a-96d6d268fb63)
网页端启动不起来
微信号: _68680
QQ:937989441

**Comment by lejianwen** [comment]
啊，不好意思，我忘记把后台打包了
我用github的actions重新打包下，我加你qq
