### ISSUE TITLE
[功能请求]地址薄内查看客户端版号

### ISSUE THREAD

**Issue by 1350962574** [lejianwen/rustdesk-api#20]
建议在地址薄内增加一列版本号，这样可以直观看到客户端的版本号
这仅仅是一个小建议
![25D15C32-298B-4EAD-B587-3575950E31E5_1_201_a](https://github.com/user-attachments/assets/64e1a746-add4-4760-bf2d-33db6ddb9b3e)

**Comment by lejianwen** [comment]
ok，我后面加一个

**Comment by 1350962574** [comment]
这真的太棒了

**Comment by 1350962574** [comment]
> ok，我后面加一个

太棒了

**Comment by lejianwen** [comment]
加上了哦~

**Comment by 1350962574** [comment]
收到！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 乐 ***@***.***&gt;
发送时间: 2024年10月28日 20:31
收件人: lejianwen/rustdesk-api ***@***.***&gt;
抄送: handsome boy ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [lejianwen/rustdesk-api] [功能请求]地址薄内查看客户端版号 (Issue #20)





 
加上了哦~
