### ISSUE TITLE
Additional build archs

### ISSUE THREAD

**Issue by shanto** [lejianwen/rustdesk-api#21]
RustDesk-API is developing very fast. It helps if more architectures are added to the build workflow. I would like to request armv7l.

CC: https://musl.cc/armv7l-linux-musleabihf-cross.tgz
GOARCH: arm
GOOS: linux

**Comment by lejianwen** [comment]
Hi, I've added armv7l, but I can't test it myself
You can try to use it, and you can give me feedback if you have any questions
Good luck

**Comment by shanto** [comment]
Tested v2.3.5-2/arm7l build. Works perfectly. Thank you!
