### ISSUE TITLE
获取组信息与地址簿失败

### ISSUE THREAD

**Issue by redjumper** [lejianwen/rustdesk-api#22]
已登录的客户端会报获取组信息与地址簿失败，不清楚具体什么时候出现的。新客户端登录也会报错，无法登录
获取组信息失败: HTTP 404, 404 page not found
![image](https://github.com/user-attachments/assets/30c9a205-8231-43f7-aa6f-fd8b9df7ad97)
获取地址簿失败: HTTP 404, 404 page not found
![image](https://github.com/user-attachments/assets/ad7001bc-b9aa-4d34-991a-6e1c0f2216a2)
环境变量如下
```
 - RUSTDESK_API_RUSTDESK_ID_SERVER=domain:xxxx
 - RUSTDESK_API_RUSTDESK_RELAY_SERVER=domain:yyyyy
 - RUSTDESK_API_RUSTDESK_API_SERVER=https://domain
 - "RUSTDESK_API_RUSTDESK_KEY=${KEY}"
 - RUSTDESK_API_APP_WEB_CLIENT=0
```

**Comment by lejianwen** [comment]
客户端版本号是多少？你这个应该是用了nginx反代，是反代的问题吗？
我测试了一下没有复现

**Comment by redjumper** [comment]
不好意思，反代的问题。redis挂了
