### ISSUE TITLE
重定向url怎么填

### ISSUE THREAD

**Issue by FangDu0606** [lejianwen/rustdesk-api#23]
![image](https://github.com/user-attachments/assets/af570f96-1a5c-4a7a-8018-62520f3ee07d)
这个重定向url怎么填呢？

**Comment by 1350962574** [comment]
https://你的域名/api/oauth/callback 或者http://你的域名/api/oauth/callback

**Comment by FangDu0606** [comment]
> [https://你的域名/api/oauth/callback](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/api/oauth/callback) 或者[http://你的域名/api/oauth/callback](http://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/api/oauth/callback)

**Comment by FangDu0606** [comment]
> [https:// 你的域名/api/oauth/callback](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/api/oauth/callback) 或者 [http:// 你的域名/api/oauth/callback](http://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/api/oauth/callback)

谢谢

**Comment by FangDu0606** [comment]
![image](https://github.com/user-attachments/assets/07904b0f-0ede-487c-95cf-476113d27566)
打开自动注册后，一个账号登录不同的设备会创建多个账号；关闭自动注册后又无法授权。请问这是怎么回事呢？

**Comment by 1350962574** [comment]
> ![image](https://private-user-images.githubusercontent.com/73295168/380042137-07904b0f-0ede-487c-95cf-476113d27566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzkyMzgsIm5iZiI6MTcyOTgzODkzOCwicGF0aCI6Ii83MzI5NTE2OC8zODAwNDIxMzctMDc5MDRiMGYtMGVkZS00ODdjLTk1Y2YtNDc2MTEzZDI3NTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2NDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYzdkNDZhNmM1MWYxYTQyODM0YTZmYjZmNzRlODk0NTIzMGI5N2U2MmM4ZDVmNTNmZGQ3MzNkYzM1NGQ0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0oliffuOYdZcKDtAl-1Zyn73yzZA-9DGOEXgrKfFdKg) 打开自动注册后，一个账号登录不同的设备会创建多个账号；关闭自动注册后又无法授权。请问这是怎么回事呢？

请检查你的配置方式是否正确

**Comment by FangDu0606** [comment]
> > ![image](https://private-user-images.githubusercontent.com/73295168/380042137-07904b0f-0ede-487c-95cf-476113d27566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzkyMzgsIm5iZiI6MTcyOTgzODkzOCwicGF0aCI6Ii83MzI5NTE2OC8zODAwNDIxMzctMDc5MDRiMGYtMGVkZS00ODdjLTk1Y2YtNDc2MTEzZDI3NTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2NDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYzdkNDZhNmM1MWYxYTQyODM0YTZmYjZmNzRlODk0NTIzMGI5N2U2MmM4ZDVmNTNmZGQ3MzNkYzM1NGQ0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0oliffuOYdZcKDtAl-1Zyn73yzZA-9DGOEXgrKfFdKg) 打开自动注册后，一个账号登录不同的设备会创建多个账号；关闭自动注册后又无法授权。请问这是怎么回事呢？
> 
> 请检查你的配置方式是否正确

我下载的文件直接./apimain运行的，然后配了github登录
![image](https://github.com/user-attachments/assets/37e5897e-e334-419b-b831-a0302965f65e)
![image](https://github.com/user-attachments/assets/73f0257f-94cb-4fee-9aab-b009c17f0f69)
您能看出来是哪的问题吗？

**Comment by 1350962574** [comment]
请提供你的配置文件

**Comment by FangDu0606** [comment]
> 请提供你的配置文件

您好，我

**Comment by FangDu0606** [comment]
> 请提供你的配置文件

![image](https://github.com/user-attachments/assets/97f9f2c9-4f3b-4c0d-8726-d6c66c83374a)
您好，我直接运行的这个文件，没有其他的配置

**Comment by 1350962574** [comment]
conf 里边有个配置文件检查一下

**Comment by FangDu0606** [comment]
> conf 里边有个配置文件检查一下

![image](https://github.com/user-attachments/assets/27117864-2d87-4380-9ac8-50092975d489)
您看看这样有问题吗？

**Comment by 1350962574** [comment]
尝试使用 Docker 部署

**Comment by FangDu0606** [comment]
> 尝试使用 Docker 部署

![image](https://github.com/user-attachments/assets/c2953ccf-a4b6-44ce-bb17-6f0bdc760704)
您好， 我使用代理docker获取失败，这该怎么弄呢

**Comment by lejianwen** [comment]
授权失败，日志里面有什么吗？

**Comment by lejianwen** [comment]
> ![image](https://private-user-images.githubusercontent.com/73295168/380042137-07904b0f-0ede-487c-95cf-476113d27566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDUyODQsIm5iZiI6MTcyOTg0NDk4NCwicGF0aCI6Ii83MzI5NTE2OC8zODAwNDIxMzctMDc5MDRiMGYtMGVkZS00ODdjLTk1Y2YtNDc2MTEzZDI3NTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyM2I5ZjA3MmNlOWU1NzAwMWIzMmZlMmE5MTA4NDQ5ZDQ1YzViODBkMjZjYjE0YzY4OTg2ZjYxOTU5YzhjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MLYuyCtu-yGolAtPRrNwtAOiCIy4xT-tepGB2-Ljdh4) 打开自动注册后，一个账号登录不同的设备会创建多个账号；关闭自动注册后又无法授权。请问这是怎么回事呢？

关闭自动注册只是会让你绑定后台账号，不会授权失败，授权失败的话有日志记录的，可以看下runtime/log.txt中的记录，会不会是网络问题？

**Comment by lejianwen** [comment]
> > 尝试使用 Docker 部署
> 
> ![image](https://private-user-images.githubusercontent.com/73295168/380077594-c2953ccf-a4b6-44ce-bb17-6f0bdc760704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDUzOTUsIm5iZiI6MTcyOTg0NTA5NSwicGF0aCI6Ii83MzI5NTE2OC8zODAwNzc1OTQtYzI5NTNjY2YtYTRiNi00NGNlLWJiMTctNmYwYmRjNzYwNzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4MzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MzQ5NTM3OTNkYjM2ZGNhZTAzYTc0Zjc3Yjk0ZDNkMjZjMDdlMmU1YjUzYzUzYzE3MGVlYTQ5ZjVhZTM0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lOQo9djN3Ui4Z_GoNxrLfc2MsW5mWCSTLNhxsYSXqgQ) 您好， 我使用代理docker获取失败，这该怎么弄呢

可以试试github的镜像

**Comment by FangDu0606** [comment]
> > ![image](https://private-user-images.githubusercontent.com/73295168/380042137-07904b0f-0ede-487c-95cf-476113d27566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDUyODQsIm5iZiI6MTcyOTg0NDk4NCwicGF0aCI6Ii83MzI5NTE2OC8zODAwNDIxMzctMDc5MDRiMGYtMGVkZS00ODdjLTk1Y2YtNDc2MTEzZDI3NTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyM2I5ZjA3MmNlOWU1NzAwMWIzMmZlMmE5MTA4NDQ5ZDQ1YzViODBkMjZjYjE0YzY4OTg2ZjYxOTU5YzhjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MLYuyCtu-yGolAtPRrNwtAOiCIy4xT-tepGB2-Ljdh4) 打开自动注册后，一个账号登录不同的设备会创建多个账号；关闭自动注册后又无法授权。请问这是怎么回事呢？
> 
> 关闭自动注册只是会让你绑定后台账号，不会授权失败，授权失败的话有日志记录的，可以看下runtime/log.txt中的记录，会不会是网络问题？

谢谢您的回复，检查了一下确实是服务器网络的问题

**Comment by lejianwen** [comment]
> 打开自动注册后，一个账号登录不同的设备会创建多个账号；关闭自动注册后又无法授权。请问这是怎么回事呢？

我自己想了一下，你这个应该是网络问题，连续同时两次授权导致重复注册了，这确实是个BUG，我后面修复下
无法授权应该是网络链接问题

**Comment by FangDu0606** [comment]
> > > 尝试使用 Docker 部署
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/73295168/380077594-c2953ccf-a4b6-44ce-bb17-6f0bdc760704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDUzOTUsIm5iZiI6MTcyOTg0NTA5NSwicGF0aCI6Ii83MzI5NTE2OC8zODAwNzc1OTQtYzI5NTNjY2YtYTRiNi00NGNlLWJiMTctNmYwYmRjNzYwNzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4MzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MzQ5NTM3OTNkYjM2ZGNhZTAzYTc0Zjc3Yjk0ZDNkMjZjMDdlMmU1YjUzYzUzYzE3MGVlYTQ5ZjVhZTM0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lOQo9djN3Ui4Z_GoNxrLfc2MsW5mWCSTLNhxsYSXqgQ) 您好， 我使用代理docker获取失败，这该怎么弄呢
> 
> 可以试试github的镜像

我不知道docker怎么获取github上的镜像(=.=!)...

**Comment by lejianwen** [comment]
`https://github.com/lejianwen/rustdesk-api/pkgs/container/rustdesk-api`
