### ISSUE TITLE
大哥，21116 这种端口能彻底更改吗？

### ISSUE THREAD

**Issue by kuufuucom** [lejianwen/rustdesk-api#25]
大哥，我的服务器是NAT共享IP模式那种，需要端口映射！ 21116这种端口开不了，有什么别的办法吗？我现在是搭建好都正常，后台用别的端口也能打开，就是手机APP设置网络地址的时候，连不上网，好像还是客户端默认21116？ 还有电脑也是点击链接还是链接的21116

![Snipaste_2024-10-27_22-15-40](https://github.com/user-attachments/assets/44431656-c38f-4a16-ac21-bf9f5ee59176)

**Comment by lejianwen** [comment]
可以填端口号啊
![image](https://github.com/user-attachments/assets/c5356f61-795e-41e1-be9e-b0478bfe469a)

**Comment by kuufuucom** [comment]
感谢，当天晚上发现了可以直接加上端口号。不过还是非常感谢您的帮助，感谢
