### ISSUE TITLE
[功能请求]希望添加一下普通注册的功能，后台可以控制是否开启

### ISSUE THREAD

**Issue by cleloo** [lejianwen/rustdesk-api#28]

**Comment by lejianwen** [comment]
可以的，我之后加个简单注册

**Comment by zhangbo8418** [comment]
> 可以的，我之后加个简单注册

是不是用户管理页面还缺个开启注册选项？

**Comment by lejianwen** [comment]
还没发版，等会晚上发一下

**Comment by lejianwen** [comment]
已更新

**Comment by zhangbo8418** [comment]
> 已更新

用户管理页面并没有 启用用户注册 选项

**Comment by zhangbo8418** [comment]
> 已更新

或者直接在信息页面修改密码下面添加个 启用用户注册checkbox？

**Comment by cleloo** [comment]
> 已更新
辛苦了，感谢，我刚试了一下发现通过改配置文件开启注册后，登录页面没有注册的跳转按钮，需要通过在链接后缀添加register才能跳转到注册，希望在优化一下，

开启注册功能的控制是否可以在这个用户管理的添加后面加一个是否开启的选项，这个选项可以控制是否允许注册及登录页注册按钮的出现隐藏。

再次感谢！
![image](https://github.com/user-attachments/assets/a54d29d6-9337-4688-873f-8bdcd26e8b41)

**Comment by lejianwen** [comment]
我后面加一个设置表吧，有些设置可以移动到数据库，直接在设置页面修改

**Comment by lejianwen** [comment]
现在是修改配置文件或者设置环境变量开启的

**Comment by lejianwen** [comment]
```
app:
  web-client: 1  # 1:启用 0:禁用
  register: false #是否开启注册
```
或者
`RUSTDESK_API_APP_REGISTER=true`

**Comment by cleloo** [comment]
> 我后面加一个设置表吧，有些设置可以移动到数据库，直接在设置页面修改

可以的，这样会比较方便，哈哈

**Comment by zhangbo8418** [comment]
> ```
> app:
>   web-client: 1  # 1:启用 0:禁用
>   register: false #是否开启注册
> ```
> 
> 或者 `RUSTDESK_API_APP_REGISTER=true`

好像没几个玩意儿可以放数据库，无非就app里面几个。。。其它选项不是要重启rustdeskserver就是要重启api，所以木有必要吧，随便找个表插入个字段得了😂
