### ISSUE TITLE
PC端链接超时的问题，希望优化。

### ISSUE THREAD

**Issue by nanqingxu** [lejianwen/rustdesk-api#29]
使用的是您的 fork的代码，现在面临一个问题，不加秘钥的话，还是链接超时。添加秘钥的话，可以连接，但是这样，收到客户端的人，就可以自己使用了。不想让别人也用。 我想客户端不加秘钥。

**Comment by lejianwen** [comment]
> 添加秘钥的话，可以连接，但是这样，收到客户端的人，就可以自己使用了。不想让别人也用。 我想客户端不加秘钥

你好，不太明白上面你说的的意思

不使用key的话，服务端好像不支持了，都强制必须使用key了，如果你想将key带入客户端，可以参考官方的编译文档，自己编译一下就可以了

**Comment by lejianwen** [comment]
> 添加秘钥的话，可以连接，但是这样，收到客户端的人，就可以自己使用了。不想让别人也用。 我想客户端不加秘钥

你好，不太明白上面你说的的意思

不使用key的话，服务端好像不支持了，都强制必须使用key了，如果你想将key带入客户端，可以参考官方的编译文档，自己编译一下就可以了

**Comment by nanqingxu** [comment]
我现在把key编译到客户端中了， 功能都使用正常， 但是这样有客户端的任何人都可以使用。 我不想让所有人都使用。有什么办法解决吗？或者在Web Admin用创建用户，只有登录账户的人才可以远程控制？

**Comment by lejianwen** [comment]
那不把KEY编译到客户端中呢?
如果你想要必须登录才能链接的话，可以参考这个项目 https://github.com/sctg-development/sctgdesk-server

**Comment by nanqingxu** [comment]
> 那不把KEY编译到客户端中呢? 如果你想要必须登录才能链接的话，可以参考这个项目 https://github.com/sctg-development/sctgdesk-server

不把key编译到客户端中，一直显示正在连接，连接不上。使用的是您的方案4： 使用[我fork的代码](https://github.com/lejianwen/rustdesk)，已经修改了secure_tcp，可以直接下载使用  克隆代码到我的仓库，然后 Github Actions编译，链接加密，不填写key 就一直正在连接，填写key几乎秒链接。
感谢，提供以上项目，我还是希望您有空了，帮我解决一下我的问题，就是客户端不内置key使用。
（使用反馈：以上情况，如果是在局域网中，有key的客户端可以链接没有key客户端的电脑。     相反使用没有key的客户端链接另外一台电脑就会提示没有key无法链接。我想要的就是这样效果。）

**Comment by lejianwen** [comment]
我还是不太明白，你是自己编译了客户端，并在编译的时候填入了key，所以你编译出来的客户端都是自带key的，是这样吗？
你自己编译客户端不要将key编译进去，在编译完成之后让用户手动填写key，应该就可以了吧
