### ISSUE TITLE
登陆后链接速度慢

### ISSUE THREAD

**Issue by FangDu0606** [lejianwen/rustdesk-api#31]
配置api服务器后，只要登录的客户端连接其他客户端建立连接的速度变慢，退出登录就恢复正常速度。这个有解决方法吗？

**Comment by lejianwen** [comment]
##### 4种解决方案
1. server端指定key。
    - 优点：简单
    - 缺点：链接不是加密的
       ```bash
       hbbs -r <relay-server-ip[:port]> -k <key>
       hbbr -k <key>
       ```
       比如
       ```bash
         hbbs -r <relay-server-ip[:port]> -k abc1234567
         hbbr -k abc1234567
       ```
2. server端使用系统生成的key，或者自定义的密钥对，但如果client已登录，链接时容易超时或者链接不上，可以退出登录后再链接就可以了，webclient可以不用退出登录
    - 优点：链接加密
    - 缺点：操作麻烦
3. server端使用系统生成的key，或者自定义的密钥对，fork官方客户端的代码将`secure_tcp`修改成直接返回，然后通过`Github Actions`编译，下载编译后的客户端。
参考[官方文档](https://rustdesk.com/docs/en/dev/build/all/)
    - 优点：链接加密，可以自定义客户端一些功能，编译后直接可用
    - 缺点：需要自己fork代码，编译，有点难度
4. 使用[我fork的代码](https://github.com/lejianwen/rustdesk)，已经修改了`secure_tcp`，可以直接下载使用，[下载地址](https://github.com/lejianwen/rustdesk/releases)
    - 优点：代码改动可查看，`Github Actions`编译，链接加密，直接下载使用
    - 缺点：可能跟不上官方版本更新
     
***对链接加密要求不高的可以使用`1`，对链接加密要求高的可以使用`3`或`4`***

**Comment by FangDu0606** [comment]
> ##### 4种解决方案
> 1. server端指定key。
>    
>    * 优点：简单
>    * 缺点：链接不是加密的
>      ```shell
>      hbbs -r <relay-server-ip[:port]> -k <key>
>      hbbr -k <key>
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      比如
>      ```shell
>        hbbs -r <relay-server-ip[:port]> -k abc1234567
>        hbbr -k abc1234567
>      ```
> 2. server端使用系统生成的key，或者自定义的密钥对，但如果client已登录，链接时容易超时或者链接不上，可以退出登录后再链接就可以了，webclient可以不用退出登录
>    
>    * 优点：链接加密
>    * 缺点：操作麻烦
> 3. server端使用系统生成的key，或者自定义的密钥对，fork官方客户端的代码将`secure_tcp`修改成直接返回，然后通过`Github Actions`编译，下载编译后的客户端。
>    参考[官方文档](https://rustdesk.com/docs/en/dev/build/all/)
>    
>    * 优点：链接加密，可以自定义客户端一些功能，编译后直接可用
>    * 缺点：需要自己fork代码，编译，有点难度
> 4. 使用[我fork的代码](https://github.com/lejianwen/rustdesk)，已经修改了`secure_tcp`，可以直接下载使用，[下载地址](https://github.com/lejianwen/rustdesk/releases)
>    
>    * 优点：代码改动可查看，`Github Actions`编译，链接加密，直接下载使用
>    * 缺点：可能跟不上官方版本更新
> 
> _**对链接加密要求不高的可以使用`1`，对链接加密要求高的可以使用`3`或`4`**_

大佬您好，用4方案的话iPhone上的客户端不能用吗

**Comment by lejianwen** [comment]
> 大佬您好，用4方案的话iPhone上的客户端不能用吗


抱歉，我没有ios系列的设备，无法提供太多帮助...
只能使用官方的了

**Comment by wsczx** [comment]
直接return Ok(());会导致key验证失效吧？这样可行吗？

**Comment by lejianwen** [comment]
> 直接return Ok(());会导致key验证失效吧？这样可行吗？

不会的，因为调用的时候基本都是有token才会调用此方法
```
  if !key.is_empty() && !token.is_empty() {
  // mainly for the security of token
  allow_err!(secure_tcp(&mut socket, key).await);
  }
```

**Comment by wsczx** [comment]
> > 直接return Ok(());会导致key验证失效吧？这样可行吗？
> 
> 不会的，因为调用的时候基本都是有token才会调用此方法
> 
> ```
>   if !key.is_empty() && !token.is_empty() {
>   // mainly for the security of token
>   allow_err!(secure_tcp(&mut socket, key).await);
>   }
> ```

这样会有问题的，这会导致客户端key直接失效，也就是说，不用key也能连了

**Comment by lejianwen** [comment]
> > > 直接return Ok(());会导致key验证失效吧？这样可行吗？
> > 
> > 
> > 不会的，因为调用的时候基本都是有token才会调用此方法
> > ```
> >   if !key.is_empty() && !token.is_empty() {
> >   // mainly for the security of token
> >   allow_err!(secure_tcp(&mut socket, key).await);
> >   }
> > ```
> 
> 这样会有问题的，这会导致客户端key直接失效，也就是说，不用key也能连了

不会啊，你想，如果你没登录API ，那么根本不会执行，也就是说这段逻辑在不使用API SERVER的时候是不需要的
