### ISSUE TITLE
Oauth自动关联用户

### ISSUE THREAD

**Issue by IamTaoChen** [lejianwen/rustdesk-api#33]
是否需要根据username或者email自动关联用户？

当前的一个测试：
1. 使用PC端进行OIDC登陆和自动注册，用户名为，user
2. 使用管理员设置user的密码
3. 使用网页登陆user，并解绑OIDC
4. PC端logout，然后重新进行OIDC登陆。结果是创建了一个新的user6

我在想当前场景是否自动关联用户，而不是重新创建user6？也许users 表添加一个字段，比如email？（github，google, oidc 都有email, 如果两者相同，则为同一个用户，这样有一个好处，就是如果设置多个IdP的话，只要email相同，则都是同一人。

但是也有一个不好的地方，如果要集成微信等其他的话，我不确定微信是否支持email字段

**Comment by lejianwen** [comment]
用户表是可以加个email, 还可以用来登录什么的
自动关联用户 感觉用email是比较好的方式，但也有些小问题
比如可能某些服务不提供email，甚至没有email，需要额外逻辑处理
还有就是很多用户有多个email，多个授权账户
也许可以保存用户的授权记录，方便再次授权的时候直接关联?



感觉就是这个自动注册的锅，关了自动注册的话，只能手动绑定就不用想这么多了...

**Comment by IamTaoChen** [comment]
关闭自动注册的话，对于每个用户都需要管理员来操作也很麻烦。
至少目前来说，email都是支持的，我们可以使用它来关联。

如果用户有多个email（比如github和google 各不相同，管理员还同时设置了github和google)->当前的解决方案好像是手动去用界面bind，但是如果两个都同时自动注册了，则需要取消绑定一个，再去绑定。

但目前的问题是，自动注册的用户不知道自己的密码（没有？）（我正在尝试让web也支持Oauth），这需要管理员来删除一个账号并设置密码，让用户登陆网页版去自己绑定。

**Comment by lejianwen** [comment]
> 如果用户有多个email（比如github和google 各不相同，管理员还同时设置了github和google)->当前的解决方案好像是手动去用界面bind，但是如果两个都同时自动注册了，则需要取消绑定一个，再去绑定。

是的，这个再次绑定只能去后台绑定，如果解绑后又直接授权登录，又会创建一个账号....

> 我先尝试让网页版支持Oauth, 然后尝试去使用email关联账户

好，感谢

**Comment by IamTaoChen** [comment]
我现在感觉oauth 现在的逻辑有些绕，实现方式，oauth信息存储以及oauth的user，我看着重构一下，可以吗？需要考虑向后兼容性吗？或者增加迁移脚本？

**Comment by lejianwen** [comment]
可以的，尽量兼容吧

**Comment by IamTaoChen** [comment]
#44

**Comment by lejianwen** [comment]
好的，谢谢，我估计要周一才能处理
