### ISSUE TITLE
请问这个注册功能咱们更新的最新功能吗？

### ISSUE THREAD

**Issue by kuufuucom** [lejianwen/rustdesk-api#35]
他这个可以让用户自己注册，是怎么实现的？ 是咱们最新功能吗？
![Snipaste_2024-10-31_08-33-31](https://github.com/user-attachments/assets/f075b803-50be-47e5-ab54-ba5a8b5c7c82)
![Snipaste_2024-10-31_08-33-22](https://github.com/user-attachments/assets/35e94d0c-04fa-49b4-9159-777f64cc1246)

**Comment by lejianwen** [comment]
注册功能正在开发，现在是管理员可以在后台直接添加用户

**Comment by lejianwen** [comment]
你截图的这个不是这个项目的啊。。。

**Comment by kuufuucom** [comment]
我看他和咱们的一样！ 还以为咱们更新新的功能了呢！

**Comment by 1350962574** [comment]
这位朋友，来错地方了吧！！！
