### ISSUE TITLE
[bug?] Empty Password for Oauth AutoRegiester

### ISSUE THREAD

**Issue by IamTaoChen** [lejianwen/rustdesk-api#37]
使用Oauth自动注册的时候，用户密码是空的，这导致了用户不能修改密码（即使不为空也不行，应为修改密码必须输入原密码）

解决方案：
* 如果密码是空，则如果用户使用Oauth登陆之后，修改密码时，原密码可以为任何？（也许仅限密码为空的时候，其他时候必须输入正确密码?）#40
* 是否有必要加一个flag在users上，比如initPassword？

**Comment by lejianwen** [comment]
那就改成密码为空的时候，旧密码可以随便填吧，感觉这样简单点 ..

**Comment by IamTaoChen** [comment]
> 那就改成密码为空的时候，旧密码可以随便填吧，感觉这样简单点 ..

OK, 我会尽快提交一个PR

**Comment by lejianwen** [comment]
辛苦辛苦 ，感谢大佬

**Comment by IamTaoChen** [comment]
管理员修改自己密码需要验证吗？在my的那个地方是需要验证的，但是在System那个重置密码是不需要的

**Comment by Ogannesson** [comment]
> 管理员修改自己密码需要验证吗？在my的那个地方是需要验证原密码，但是在System那个重置密码是不需要的

在my那是走的ChangeCurPwd，用的是当前用户的令牌，需要验证旧密码，属于用户功能。
system那是UpdatePassword，前置校验管理员权限，修改所有用户包括管理员的密码都没有验证，属于管理员功能。
我觉得逻辑很清晰，没啥问题
