### ISSUE TITLE
能否添加一个功能：控制端必须登录后才能发起连接。

### ISSUE THREAD

**Issue by lishuwei198663** [lejianwen/rustdesk-api#41]
现在的情况是，如果别人拿到我这个通过编译集成了服务器IP和KEYR的客户端，都可以实现主控电脑，如果刚好他又有被控端的程序。

那么别人就有了一套可以任意使用的远程主控端和被控端，这我在服务端里却无法控制，因为我的很多被控端都是随机生成ID的，不知道哪个ID是哪台电脑。

如果添加了  控制端必须登录后才能发起连接  这个功能后，我可以通过后台帐号定期更换密码来控制主控端。

谢谢，祝您生活愉快！

**Comment by lejianwen** [comment]
你好，这需要修改server端才能做到，官方开源版本没这个功能，pro版有。你也可以查看其他开源版
比如 https://github.com/sctg-development/sctgdesk-server

**Comment by lishuwei198663** [comment]
好的，谢谢
