### ISSUE TITLE
when I call api address_book, online status alway false

### ISSUE THREAD

**Issue by B-YS** [lejianwen/rustdesk-api#43]
when I call api address_book, online status alway false. Is it bug or I build wrong?

**Comment by lejianwen** [comment]
Which API exactly? Can you provide more detailed information?

**Comment by B-YS** [comment]
this api "http://localhost:21114/api/admin/address_book/list?page=1&page_size=10&is_my=1" online alway response false ""online": false,
                "loginName": "",
                "sameServer": false,
                "collection_id": 0,"

**Comment by lejianwen** [comment]
this field is invalid, you can use 'http://127.0.0.1:21114/api/admin/peer/list'
`last_online_time` is ok
