### ISSUE TITLE
[bug] normal user can delete peer

### ISSUE THREAD

**Issue by IamTaoChen** [lejianwen/rustdesk-api#45]
无意中发现普通用户可以删除peer.

我在“My”中增加了“我的设备”，普通用户点击删除的时候，把设备删除了。我还没时候后端的API，按理说应该使用Admin鉴权会失败

**Comment by lejianwen** [comment]
怎么新增"我的设备"？是pc端吗？还是说地址簿？

**Comment by IamTaoChen** [comment]
> 怎么新增"我的设备"？是pc端吗？还是说地址簿？

其实就是吧Peers那个界面复制了一份到my那儿，然后吧list端点改成了/user/myPeer 只获取当前用户的Peers

**Comment by lejianwen** [comment]
是的，是BUG，权限判断放错地方了，之前估计是想着有`我的设备`
我修复一下
