### ISSUE TITLE
[问题反馈] 

### ISSUE THREAD

**Issue by 1350962574** [lejianwen/rustdesk-api#50]
# 设备管理
 将对应的已登录的设备进行删除，貌似对应的设备仍然处于登录状态并没有登出
<img src="https://github.com/user-attachments/assets/b12e71d4-1c82-4417-a1bd-9fa7bcc6b921">

# 在线心跳异常
对应的 ID 处于在线状态，但客户端显示一会在线一会离线，或者需要在当前界面等待一定的时间才刷新在线状态，实际下边视频中ID 都是处于在线状态的

https://github.com/user-attachments/assets/8a17ce04-ae36-4502-86bc-d1999cd81b37

**Comment by lejianwen** [comment]
> 将对应的已登录的设备进行删除，貌似对应的设备仍然处于登录状态并没有登出

删除后应该是退出了， 看你这个像是他又登录了，然后就自动创建了一个设备

> 在线心跳异常

这个应该是客户端/服务端或者网络的问题，因为API SERVER影响不了这个

**Comment by 1350962574** [comment]
居然是云WAF误杀
