### ISSUE TITLE
更新245版本后Google Oauth似乎没有迁移成功

### ISSUE THREAD

**Issue by Ogannesson** [lejianwen/rustdesk-api#51]
更新245版本后使用Google Oauth时出现了 `failed to fetch OlDC configuration`
![image](https://github.com/user-attachments/assets/858bfb24-e32c-4fca-b493-e66b1e40d4f7)
日志为
`2024-11-05 10:47:31 [WARN] LocalizeMessage Error: message "failed to fetch OIDC configuration" not found in language "zh-CN" (/home/runner/work/rustdesk-api/rustdesk-api/http/response/response.go:64 Gwen/http/response.TranslateMsg)`
GitHub登录正常

**Comment by lejianwen** [comment]
是不是访问google失败了？

**Comment by Ogannesson** [comment]
> 是不是访问google失败了？

应该不是，我这是走了代理的，等我把sqlite拉下来看看表吧。

**Comment by lejianwen** [comment]
我试了不走代理就会这样
嗯，先看看数据是啥样的
麻烦了

**Comment by Ogannesson** [comment]
我暂时没看出数据库有什么问题，但问题应该不在网络上，尝试Github登录的请求是成功走代理完成了的。

**Comment by lejianwen** [comment]
关掉代理之后我的也会这样
![image](https://github.com/user-attachments/assets/9ede5063-dce2-4f81-a3a9-ed5b358092b0)
![image](https://github.com/user-attachments/assets/27177f84-f87a-469e-88c0-43ab522cc598)

**Comment by lejianwen** [comment]
![image](https://github.com/user-attachments/assets/78a2e2aa-8859-4a6a-a679-54d5920c1484)
google这个数据有issuer吗？

**Comment by Ogannesson** [comment]
> 引用到新

没有

**Comment by Ogannesson** [comment]
问题似乎就在issuer，配置Google时没有填写issuer，但`GetOauthConfig`方法在 `case model.OauthTypeOidc`, `model.OauthTypeGoogle` 分支中调用 `FetchOidcEndpoint()`。如果 issuer 无效或无法正确解析就会抛出`failed to fetch OIDC configuration`

**Comment by lejianwen** [comment]
可以截图看下数据是什么样的吗？非常感谢！clientid之类的打码

**Comment by Ogannesson** [comment]
其余项应该没什么问题，但issuer是空的
![屏幕截图 2024-11-05 204748](https://github.com/user-attachments/assets/a9e13b51-8e7a-45ad-93da-67be75527d19)

**Comment by Ogannesson** [comment]
我看了一下迁移代码，很奇怪的是其余迁移都正常完成了，versions表也正常更新了，但issuser字段还是空的
![image](https://github.com/user-attachments/assets/12961e29-9b38-45d3-8093-fbbe673dc2a3)

**Comment by Ogannesson** [comment]
> 我知道了，原来的issuer不是空是null，因为我sql是`update oauths set issuer = 'https://accounts.google.com' where op = 'google' and issuer = ''`， 我改下，把`issuer=''`去掉
原来如此，我拿备份试验了几次，一直不行，我还纳闷来着

**Comment by lejianwen** [comment]
我也是用备份实验，因为我的备份数据之前一直是空置... 蛋疼

**Comment by lejianwen** [comment]
谢谢大佬的帮助

**Comment by Ogannesson** [comment]
没事，你也辛苦了

**Comment by lejianwen** [comment]
我更新了，246，你更新下试试

**Comment by Ogannesson** [comment]
我拿备份试了一下，OK了
