### ISSUE TITLE
Temporary Solution to Address Slow Connection Issues in RustDesk

### ISSUE THREAD

**Issue by IamTaoChen** [lejianwen/rustdesk-api#54]
**Connection issues or timeouts**: Because the server version lags behind the client version, the server does not respond to the client’s secure_tcp requests, causing the client to experience timeouts. The relevant code in the RustDesk client can be found [here](https://github.com/rustdesk/rustdesk/blob/master/src/client.rs#L322).

To address this issue from the server side, a PR has been created to add secure TCP support specifically for the RustDesk server: [rustdesk-server PR #400](https://github.com/rustdesk/rustdesk-server/pull/400).

I have forked the repository and integrated this PR into my own branch: [IamTaoChen’s rustdesk-server with STCP](https://github.com/IamTaoChen/rustdesk-server/tree/stcp). This modified version appears to resolve the connection issues effectively.

The Docker image for this updated server version is available at [iamtaochen/rustdesk-server:stcp](https://hub.docker.com/r/iamtaochen/rustdesk-server).

	Note: This solution is specifically for the RustDesk server and does not involve changes to the RustDesk client.

**Comment by IamTaoChen** [comment]
**连接问题或超时**：由于服务器版本落后于客户端版本，服务器无法响应客户端的 secure_tcp 请求，导致客户端出现超时问题。RustDesk 客户端中的相关代码可以在[此处](https://github.com/rustdesk/rustdesk/blob/master/src/client.rs#L322)找到。

为了解决这个问题，此方法从服务器端入手，一个 PR 已经创建，用于在 RustDesk 服务器中添加对安全 TCP 的支持：[rustdesk-server PR #400](https://github.com/rustdesk/rustdesk-server/pull/400)。

我已经 fork 了该仓库，并将这个 PR 合并到了我自己的分支中：[IamTaoChen 的 rustdesk-server with STCP](https://github.com/IamTaoChen/rustdesk-server/tree/stcp)。这个修改版本似乎有效地解决了连接问题。

这个更新版本的服务器 Docker 镜像可以在 [iamtaochen/rustdesk-server:stcp](https://hub.docker.com/r/iamtaochen/rustdesk-server) 获取。

	注意：该解决方案仅针对 RustDesk 服务器，未涉及对 RustDesk 客户端的更改。

**Comment by IamTaoChen** [comment]
也许可以把这个放在讨论里？

**Comment by lejianwen** [comment]
> 也许可以把这个放在讨论里？

都行

**Comment by IamTaoChen** [comment]
> > **Connection issues or timeouts**: Because the server version lags behind the client version, the server does not respond to the client’s secure_tcp requests, causing the client to experience timeouts. The relevant code in the RustDesk client can be found [here](https://github.com/rustdesk/rustdesk/blob/master/src/client.rs#L322).
> > To address this issue from the server side, a PR has been created to add secure TCP support specifically for the RustDesk server: [rustdesk-server PR #400](https://github.com/rustdesk/rustdesk-server/pull/400).
> > I have forked the repository and integrated this PR into my own branch: [IamTaoChen’s rustdesk-server with STCP](https://github.com/IamTaoChen/rustdesk-server/tree/stcp). This modified version appears to resolve the connection issues effectively.
> > The Docker image for this updated server version is available at [iamtaochen/rustdesk-server:stcp](https://hub.docker.com/r/iamtaochen/rustdesk-server).
> > ```
> > Note: This solution is specifically for the RustDesk server and does not involve changes to the RustDesk client.
> > ```
> 
> Thank you for the solution! Can you please also create a arm64 image?

I'm trying to build arm64 image, can you try this image `iamtaochen/rustdesk-server:arm64`?

**Comment by wy414012** [comment]
@IamTaoChen  我把这个PR中 windows 客户端构建损坏的问题也修了，https://github.com/wy414012/rustdesk-server  现在全客户端好使了，docker镜像也是全推送的，顺便修了下官方的bug，你可以将tcp-encrypt分支中的代码合并过去即可解决你构建失败的bug,其它两个分支的代码，不要去尝试合并，那是用于测试修复的，完全打破了的，甚至混淆很严重。至于CI检查过不去的bug是因为代码中有很多陈旧的1.70.0之前版本的遗留bug，我会抽时间给修复，目前我将代码环境全部提升到了1.82.0版本来开发，补全缺失的功能，现在配合这个api工作的会很好，(docker镜像)[https://hub.docker.com/repository/docker/wy368/openrustdesk-server/tags] 在这里。

**Comment by saros-cpu** [comment]
Sharing a production-verified fix for the same problem on WINDOWS (native, no Docker).

I used IamTaoChen/rustdesk-server (stcp branch, v1.1.12) and compiled hbbs/hbbr for Windows via GitHub Actions, then replaced the NSSM services on the server. After deploying, clients logged into the address book connect instantly again - same as before using the API. Zero client changes.

Key points for Windows builds:
1. workflow: windows-2022 + Rust 1.85.0
2. git clone --depth 1 --branch stcp https://github.com/IamTaoChen/rustdesk-server.git .
3. IMPORTANT build fix: libs/hbb_common/Cargo.toml enables winapi features ["winuser","synchapi","pdh","memoryapi"] but platform/windows.rs uses winapi::um::sysinfoapi::VerSetConditionMask - building fails with E0432. Add "sysinfoapi" to the feature list:
   features = ["winuser", "synchapi", "pdh", "memoryapi", "sysinfoapi"]
4. cargo build --release --all-features --target x86_64-pc-windows-msvc
   -> hbbs.exe / hbbr.exe / rustdesk-utils.exe (v1.1.12)
5. Deploy: stop hbbs/hbbr (NSSM) -> backup -> replace 3 exe -> restart. Keep id_ed25519 untouched (all client IDs unchanged).

The missing sysinfoapi feature is a genuine build bug in the stcp branch; I'd suggest adding it upstream so Windows builds work out of the box.
