### ISSUE TITLE
check the condition of binding peer with user

### ISSUE THREAD

**Issue by IamTaoChen** [lejianwen/rustdesk-api#55]
今天使用webclient登陆的时候，发现web端也在peer中了（这是我引入的一个bug, https://github.com/lejianwen/rustdesk-api/commit/4f616ffff16bd146cade05c836707182073b1e6b ,为了让设备登陆的时候自动绑定用户，当时的考虑是 device 同步信息太慢，用户登陆设备就可以绑定设备，这样快捷一些）。 我觉应该不在里面会更好吧？

新建一个函数来判断是否shouldAddToPeer 或者 ShouldBindPeerToUser？

下面两种哪种判断更合理一些？后者？

```go
// If the uuid is not empty and the login type is not web and webadmin, bind the uuid to the user
 if llog.Uuid != "" && llog.Type != model.LoginLogClientWeb && llog.Type != model.LoginLogClientWebAdmin {
    AllService.PeerService.UuidBindUserId(llog.DeviceId, llog.Uuid, u.Id)
}
// If the uuid is not empty and the login type is app, bind the uuid to the user
if llog.Uuid != "" && llog.Type == model.LoginLogClientApp {
    AllService.PeerService.UuidBindUserId(llog.DeviceId, llog.Uuid, u.Id)
}

```

**Comment by lejianwen** [comment]
webclient登录 不会增加peer啊，因为webclient没有带UUID，你是用的v2版本的？
webadmin使用oauth登录会带uuid，我已经去掉了

我觉得在登录的时候，如果有UUID，查询设备，如果设备不存在，不应该新增设备，因为这个是时候设备很多信息是空缺的

**Comment by IamTaoChen** [comment]
我使用v2的，使用密码登陆的。我登陆的时候去世添加进去了，我在check一下
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/4d8ba6dc-1d3f-4542-9bcd-3d859847609c">

**Comment by lejianwen** [comment]
嗯 v2版本会在登录的时候传uuid

**Comment by lejianwen** [comment]
我觉得先改成: 登录时如果此uuid的设备不存在则不进行创建吧
一般来说启动PC客户端的时候会上传 设备信息，API响应上传成功后，就不会再上传了，直到下次启动客户端。
上传设备信息 的时候我记得我会检查最后一次登录该设备的用户并绑定
