### ISSUE TITLE
Web Client 一直提示链接注册服务器失败

### ISSUE THREAD

**Issue by frank-wxs** [lejianwen/rustdesk-api#58]
原因猜测是因为 WebSocket connection to 'wss://xxx.com:21118/' failed

我的版本为 rustdesk-server 1.1.12

**Comment by lejianwen** [comment]
你看下是不是这个原因 https://github.com/lejianwen/rustdesk-api/issues/11

**Comment by lejianwen** [comment]
好的，现在web client v2 preview 放上去了，你可以试试v2的

**Comment by Kbstsn** [comment]
> 好了，现在web客户端v2预览放上去了，你可以试试v2的
V2不需要SSL反代21118和21119端口吗？为啥我还是连接不成功

**Comment by lejianwen** [comment]
> > 好了，现在web客户端v2预览放上去了，你可以试试v2的
> > V2不需要SSL反代21118和21119端口吗？为啥我还是连接不成功

你看下这个能解决不https://github.com/lejianwen/rustdesk-api/wiki/Web-Client-V2-Preview-Document
