### ISSUE TITLE
WebClient可以在URL中带上账号及密码，实现自动登录吗？

### ISSUE THREAD

**Issue by Salem-Su** [lejianwen/rustdesk-api#6]
比如:http://webclient IP/webclient/?user=abc&password=abc&id=12345678

**Comment by lejianwen** [comment]
如果你在PC端保存了密码，并连成功后，密码会同步到后台，webclient也会从后台获取到密码

**Comment by Salem-Su** [comment]
谢谢，其实我是想让WebClient登录，就类似自动点击右WebClient上角的Login一样

**Comment by lejianwen** [comment]
你是想将这个分享给 未登录的用户(比如游客) ? 然后他们可以直接点击，就自动登录远程的机器？

**Comment by Salem-Su** [comment]
是的，你太对了，哈哈

**Comment by lejianwen** [comment]
已经可以了，在后台地址簿有个分享功能，点击后
就可以生成链接，然后复制发给别人了
![image](https://github.com/user-attachments/assets/0572e1ec-7a22-48a2-b6c7-f300a69cd52a)

**Comment by Salem-Su** [comment]
太感谢大神的付出了！
