### ISSUE TITLE
怎么实现填入多server自动则优？

### ISSUE THREAD

**Issue by zxm82081372** [lejianwen/rustdesk-api#61]
因为有海外的设备，想实现在客户端填入多个中转服务器，自动选择最优路线，不知道有什么方法？

**Comment by lejianwen** [comment]
不太明白什么场景，多个client, 多个server？
在client 中填写最优路线的relay server可行？

**Comment by IamTaoChen** [comment]
当前，如果被控制客户端没有指定中继服务器，应该是随机从多个中继服务器中选一个（如果不通，则切换下一个）。如果被控客户端指定了中继服务器，则会强制使用这个中继服务器。

要实现自动选优的话，需要修改ID服务器中的代码来实现此功能

**Comment by zxm82081372** [comment]
> 不太明白什么场景，多个client, 多个server？ 在client 中填写最优路线的relay server可行？

是的，多个server，比如欧洲服务器、东南亚服务器，保证远程时延迟。你说的也是个方法哈，做一个列表让用户选择自己的区域也可以。

**Comment by zxm82081372** [comment]
> 当前，如果被控制客户端没有指定中继服务器，应该是随机从多个中继服务器中选一个（如果不通，则切换下一个）。如果被控客户端指定了中继服务器，则会强制使用这个中继服务器。
> 
> 要实现自动选优的话，需要修改ID服务器中的代码来实现此功能

这样的啊？我用的是docker compose部署的，在ID服务器可以指定多个中继服务器吗？
