### ISSUE TITLE
一直print token

### ISSUE THREAD

**Issue by IamTaoChen** [lejianwen/rustdesk-api#62]
有个小问题，console一直在打印token

<img width="653" alt="image" src="https://github.com/user-attachments/assets/6ea852f3-e761-4925-9454-70afa461d014">
<img width="547" alt="image" src="https://github.com/user-attachments/assets/00609a6d-fb7a-44a0-94ef-f6a81e92f862">

**Comment by lejianwen** [comment]
好的，我去掉一下
