### ISSUE TITLE
后台使用 webclient2 不正常

### ISSUE THREAD

**Issue by zzkuner** [lejianwen/rustdesk-api#64]
回跳转到这里
http://192.168.1.66:21114/webclient2/#/1507856049
我把http://192.168.1.66:21114换成反代后的域名就可以了
这个原因是什么

**Comment by lejianwen** [comment]
是不是没配置`RUSTDESK_API_RUSTDESK_API_SERVER`
`RUSTDESK_API_RUSTDESK_API_SERVER`的默认值是`http://192.168.1.66:21114`，这个确实是个bug，我去掉一下

**Comment by zzkuner** [comment]
我直接用的咱们的示例：
  rustdesk-api:
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.1.66:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.1.66:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://192.168.1.66:21114
      - RUSTDESK_API_RUSTDESK_KEY=desk.zzk.zone

    ports:
      - 21114:21114
    image: lejianwen/rustdesk-api
    volumes:
      - /data/rustdesk/api:/app/data #将数据库挂载出来方便备份
    networks:
      - rustdesk-net
    restart: unless-stopped

**Comment by lejianwen** [comment]
就是你部署的API的地址
![image](https://github.com/user-attachments/assets/cd667106-d876-4ceb-b41c-07ca99b6b83f)

**Comment by zzkuner** [comment]
好的，感谢您！

**Comment by lejianwen** [comment]
客气了
