### ISSUE TITLE
Add Support for Spanish Translations

### ISSUE THREAD

**Issue by aelogonpin** [lejianwen/rustdesk-api#65]
Greetings =).
I would like to propose to add support for Spanish translations to this project. I think this would help broaden the scope of the tool and make it accessible to a wider Spanish-speaking audience. I am willing to contribute by working on the initial translations to establish support for this language.

If any action is needed I would be happy to help.

Thank you very much!!!!!

![image](https://github.com/user-attachments/assets/74307150-4ce2-4cda-9572-5e91976553b0)

**Comment by lejianwen** [comment]
This is a great suggestion.  
I will use ChatGPT to provide translation support for the Spanish language.  
It may not be entirely accurate, and PRs for corrections are welcome.  

Thank you very much!

**Comment by lejianwen** [comment]
Spanish language has been supported~
![image](https://github.com/user-attachments/assets/93b2b04b-9a24-4b7c-b863-4d4456fd0ecd)

**Comment by aelogonpin** [comment]
Spectacular!!!!!.

As soon as I can, I'll start translating and I'll send you the PR.
Thank you very much for your contribution =)
