### ISSUE TITLE
webclient2报错，麻烦看下

### ISSUE THREAD

**Issue by cleloo** [lejianwen/rustdesk-api#67]
我使用直接编译好的运行的，配置文件都改过的，其他功能也都正常，就是访问webclient2链接不上，然后会提示一个rustdesk官方的一个地址访问不了，这个在哪里改呢？
![微信截图_20241128095343](https://github.com/user-attachments/assets/b68cd92a-a2cb-4f77-99cf-c52fb8080026)

**Comment by lejianwen** [comment]
看上去是没配置好中继服务器，pc客户端的配置 可否发一下？

**Comment by cleloo** [comment]
找到原因了，我是用的反代的域名，把配置文件里面的端口号去掉就正常了
