### ISSUE TITLE
后台批量处理功能需求

### ISSUE THREAD

**Issue by yczhl21** [lejianwen/rustdesk-api#69]
1、为安全性，避免太多token数据，批量删除 用户 token列表
2、设备管理 中 多选、批量添加到某一地址簿，修改标签
3、设备管理、地址簿 中 多选、批量修改标签
4、请问 API中 增加到地址簿 是哪个接口地址

**Comment by lejianwen** [comment]
1. ok
2. 只能在`我的设备` 里面添加此功能，因为每个人的标签不一样
3. 同上
4. `/ab/peer/add/{guid}`
