### ISSUE TITLE
功能提议

### ISSUE THREAD

**Issue by 1350962574** [lejianwen/rustdesk-api#71]
`我的设备`中是否可以添加备注或者别名以方便区分已登录的设备
![IMG_6571](https://github.com/user-attachments/assets/e76efc25-5099-45b4-a450-ed8070681744)

**Comment by lejianwen** [comment]
备注或者别名是在 `地址簿` 上
设备可能存在在多个地址簿中，不能使用地址簿的备注
设备上加这个字段的话，只能在后台编辑修改和显示，感觉没有必要
