### ISSUE TITLE
Login fail and desktop app crash in Windows 7 64bit

### ISSUE THREAD

**Issue by dbucci69** [lejianwen/rustdesk-api#76]
Hi all, I experienced a desktop app (version 1.3.5) close or crash in Windows 7 Home Premium 64 bit when try to establish a connection to your api server (Connect to Addressbook). I don't know if the issue is in app (maybe) or in the api-server. If someone can investigate I'll appreciate much. Thank you, Davide

**Comment by lejianwen** [comment]
api-server shouldn't cause the app to crash
Is everything fine when not using api-server?
It may be that the app is not compatible with Windows 7

**Comment by dbucci69** [comment]
Yes, you right as I thought. Api server can't block the desktop client, so, all other things work well, I can connect to remote and manage the basic features. I'll try to investigate in desktop client. Do you think it is reasonable write this to the Rustdesk main git? I think not....

**Comment by lejianwen** [comment]
> Do you think it is reasonable write this to the Rustdesk main git?

Also i think not....
