### ISSUE TITLE
Rustdesk客户端问题请教

### ISSUE THREAD

**Issue by Salem-Su** [lejianwen/rustdesk-api#77]
有没有办法让客户端能静默接受远程连接？比如有一个默认的密码，不需要手动设置一次

**Comment by lejianwen** [comment]
自己编译应该可以？

**Comment by yczhl21** [comment]
编译太麻烦，自己做一个脚本就可以，可以自动下载安装、配置连接信息及默认密码，并可使用接口发送钉钉推送，看你怎么折腾
这是我写的批处理，配置自己的信息让对方 运行就可以

@echo off

setlocal ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION


set rustdesk_pw=连接密码
set rustdesk_cfg="配置信息字符串"

rem pause

set "RDPath=C:\Program Files\RustDesk\rustdesk.exe"
if exist "%RDPath%" (
	mode con cols=60 lines=12
	c:
	cd ..
	cd "C:\Program Files\RustDesk\"
	for /f "delims=" %%i in ('rustdesk.exe --get-id ^| more') do set rustdesk_id=%%i

	net start RustDesk
	cls
	choice /t 2 /d y /n >nul

	rustdesk.exe --config %rustdesk_cfg%
	rustdesk.exe --password %rustdesk_pw%

	start " " rustdesk.exe
	
	rem pause
	
) else (
	mode con cols=90 lines=12
	echo .
	echo 正在下载文件，请稍等。。。。
	echo ---------------------------------------------------------------------------
	if not exist C:\Temp\ md C:\Temp\
	powershell -Command "Invoke-WebRequest -Uri "http://www.xxx.com/rustdesk.exe" -OutFile "C:\Temp\rustdesk.exe"
	
	choice /t 2 /d y /n >nul
	
	mode con cols=60 lines=12
	cls
	echo .
	echo 正在安装。。。。
	echo --------------
	c:
	cd ..
	cd C:\Temp\
	rustdesk.exe --silent-install
	choice /t 5 /d y /n >nul
	
	
	cd "C:\Program Files\RustDesk\"
	rustdesk.exe --install-service
	choice /t 5 /d y /n >nul

	for /f "delims=" %%i in ('rustdesk.exe --get-id ^| more') do set rustdesk_id=%%i

	net start RustDesk
	cls
	choice /t 2 /d y /n >nul

	rustdesk.exe --config %rustdesk_cfg%
	rustdesk.exe --password %rustdesk_pw%

	start " " "C:\Program Files\RustDesk\rustdesk.exe"

)


::send dingmsg
setlocal enabledelayedexpansion
set "myComputerName=%COMPUTERNAME%"

set "url=http://www.xxx.com/rustdeskuri.php?type=ding&pcname=!myComputerName!&rudeskid=!rustdesk_id!"
powershell -Command "Invoke-RestMethod -Uri '%url%' -Method Get"



cls
echo ............%myComputerName%.....................
echo.
echo 请将远程ID： %rustdesk_id% 及 一次性密码 截图 或拍图
echo.
echo 发送给对方，方便快速远程
echo.
echo 注意屏幕右上方，如有提示【 接受 】，请点击
echo.
echo ...............................................
echo.
echo.

pause

**Comment by yczhl21** [comment]
我的方式是根据官方的写脚本，配置 自己的信息，发送给对方 运行就可以，只要是杀毒是否影响 运行，
可以自动下载并安装，配置 、并可推送到钉钉等方式 ，看自己如何折腾


> 自己编译应该可以？

你好，能否再优化功能
1、增加共享查询功能 share_records ，可删除或停用共享
2、在 系统-设备管理 中面多选后，批量增加到地址簿 功能

**Comment by lejianwen** [comment]
> 我的方式是根据官方的写脚本，配置 自己的信息，发送给对方 运行就可以，只要是杀毒是否影响 运行， 可以自动下载并安装，配置 、并可推送到钉钉等方式 ，看自己如何折腾
> 
> > 自己编译应该可以？
> 
> 你好，能否再优化功能 1、增加共享查询功能 share_records ，可删除或停用共享 2、在 系统-设备管理 中面多选后，批量增加到地址簿 功能

嗯
1. 忘记加了，
2. 这个批量添加到地址簿，逻辑上感觉没什么必要啊

**Comment by yczhl21** [comment]
因为帐号里地址簿主要来源
1、人工收藏
2、设备列表里单个增加
现在需求是某帐号下需要根据hostname选择某一批量设备增加到该 帐号下的地址簿

**Comment by lejianwen** [comment]
> 因为帐号里地址簿主要来源 1、人工收藏 2、设备列表里单个增加 现在需求是某帐号下需要根据hostname选择某一批量设备增加到该 帐号下的地址簿

好，我加一个

**Comment by lejianwen** [comment]
> 因为帐号里地址簿主要来源 1、人工收藏 2、设备列表里单个增加 现在需求是某帐号下需要根据hostname选择某一批量设备增加到该 帐号下的地址簿

更新了，应该可以了
