### ISSUE TITLE
客户端登录账户时，发起连接超时

### ISSUE THREAD

**Issue by shixinwu** [lejianwen/rustdesk-api#78]
具体表现是一直转圈，
![QQ_1733908688181](https://github.com/user-attachments/assets/673d8a68-f92d-4574-b197-1a85b7ffd628)
查看日志发现，再不停的建立中继，然后断开
![QQ_1733908787605](https://github.com/user-attachments/assets/4e9846e6-ab9b-42f5-8f39-8112660d26f5)

只要退出账户，就可以恢复正常连接

**Comment by lejianwen** [comment]
https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6

**Comment by wy414012** [comment]
@lejianwen 建议使用我的修改方式，保留key验证，直接修改移除验证太暴力了，对了哥们你代码能不能写点注释啊，我想将你的web客户端做个PR，看了好几天没看明白，你的代码逻辑，有点尴尬
### 修改后的代码在这里：
https://github.com/wy414012/rustdesk/blob/api-support/src/common.rs#L1234

> https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6

**Comment by lejianwen** [comment]
> @lejianwen 建议使用我的修改方式，保留key验证，直接修改移除验证太暴力了，对了哥们你代码能不能写点注释啊，我想将你的web客户端做个PR，看了好几天没看明白，你的代码逻辑，有点尴尬
> 
> ### 修改后的代码在这里：
> https://github.com/wy414012/rustdesk/blob/api-support/src/common.rs#L1234
> 
> > https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6

```
  if !key.is_empty() && !token.is_empty() {
  // mainly for the security of token
  allow_err!(secure_tcp(&mut socket, key).await);
  }
```

`secure_tcp`是在`!token.is_empty()`才会执行，不用API SERVER根本不会走这一步

你这个保留KEY验证，其实就只是进行了一次base64解码验证吧

`web客户端`你是说v2版本吗？v2版本没有源码，我也是从官网扣下来的，然后改改

**Comment by wy414012** [comment]
> > @lejianwen 建议使用我的修改方式，保留key验证，直接修改移除验证太暴力了，对了哥们你代码能不能写点注释啊，我想将你的web客户端做个PR，看了好几天没看明白，你的代码逻辑，有点尴尬
> > ### 修改后的代码在这里：
> > https://github.com/wy414012/rustdesk/blob/api-support/src/common.rs#L1234
> > > https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6
> 
> ```
>   if !key.is_empty() && !token.is_empty() {
>   // mainly for the security of token
>   allow_err!(secure_tcp(&mut socket, key).await);
>   }
> ```
> 
> `secure_tcp`是在`!token.is_empty()`才会执行，不用API SERVER根本不会走这一步
> 
> 你这个保留KEY验证，其实就只是进行了一次base64解码验证吧
> 
> `web客户端`你是说v2版本吗？v2版本没有源码，我也是从官网扣下来的，然后改改

是的 我也重官方的容器里面拿，nginx代理的方式 准备改成和官方wss逻辑一致走但是我没看明白你那个接入逻辑，还没有动手。

**Comment by lejianwen** [comment]
> > > @lejianwen 建议使用我的修改方式，保留key验证，直接修改移除验证太暴力了，对了哥们你代码能不能写点注释啊，我想将你的web客户端做个PR，看了好几天没看明白，你的代码逻辑，有点尴尬
> > > ### 修改后的代码在这里：
> > > https://github.com/wy414012/rustdesk/blob/api-support/src/common.rs#L1234
> > > > https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6
> > 
> > 
> > ```
> >   if !key.is_empty() && !token.is_empty() {
> >   // mainly for the security of token
> >   allow_err!(secure_tcp(&mut socket, key).await);
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `secure_tcp`是在`!token.is_empty()`才会执行，不用API SERVER根本不会走这一步
> > 你这个保留KEY验证，其实就只是进行了一次base64解码验证吧
> > `web客户端`你是说v2版本吗？v2版本没有源码，我也是从官网扣下来的，然后改改
> 
> 是的 我也重官方的容器里面拿，nginx代理的方式 准备改成和官方wss逻辑一致走但是我没看明白你那个接入逻辑，还没有动手。

那直接用官方的js就可以了，我没改什么逻辑，只是加了从api获取id server配置，不用也行，用的时候自己填就行

**Comment by wy414012** [comment]
> > > > @lejianwen 建议使用我的修改方式，保留key验证，直接修改移除验证太暴力了，对了哥们你代码能不能写点注释啊，我想将你的web客户端做个PR，看了好几天没看明白，你的代码逻辑，有点尴尬
> > > > ### 修改后的代码在这里：
> > > > https://github.com/wy414012/rustdesk/blob/api-support/src/common.rs#L1234
> > > > > https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6
> > > 
> > > 
> > > ```
> > >   if !key.is_empty() && !token.is_empty() {
> > >   // mainly for the security of token
> > >   allow_err!(secure_tcp(&mut socket, key).await);
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `secure_tcp`是在才会执行，不用API SERVER根本不会走这一步 你这个保留KEY验证，其实就只是进行了一次base64解码验证吧 你是说v2版本吗？v2版本没有源码，我也是从官网扣下来的，然后改改`!token.is_empty()``web客户端`
> > 
> > 
> > 是的 我也重官方的容器里面拿，nginx代理的方式 准备改成和官方wss逻辑一致走但是我没看明白你那个接入逻辑，还没有动手。
> 
> 那直接用官方的js就可以了，我没改什么逻辑，只是加了从api获取id server配置，不用也行，用的时候自己填就行
我以为你是加了什么逻辑判断才全部走的 / 我的由于直接在服务器部署的，所以端口不是那么灵活 所以需要用官方的方式都走同一个端口 代理到后端上

**Comment by lejianwen** [comment]
> 我以为你是加了什么逻辑判断才全部走的 / 我的由于直接在服务器部署的，所以端口不是那么灵活 所以需要用官方的方式都走同一个端口 代理到后端上

我是在官方的基础上多加了个端口模式，因为有些用户不能反代路径或者使用443端口
可以看看这个 https://github.com/lejianwen/rustdesk-api/wiki/HTTPS-Reverse-Proxy
