### ISSUE TITLE
web安全

### ISSUE THREAD

**Issue by xw-l** [lejianwen/rustdesk-api#8]
你好大佬，如何保证web界面的安全呢，我开始想限制某个IP访问的，发现所有客户端都要访问web端口才能显示，类似于被动

**Comment by lejianwen** [comment]
你好，我没太明白你说的是什么意思。
限制某个IP的话，可以通过防火墙规则
或者前面加一层nginx反代，nginx中将IP限制

**Comment by xw-l** [comment]
是这样的，当我执行 iptables -s x.x.x.x/32 -p tcp --dport 21114 -j ACCEPT,限制智能该IP访问21114端口时，登陆成功但不会显示客户端的信息，当我去掉-s，也就是放通所有，才会显示客户端，我是公网环境，如果是这样的话，我每个客户端都需要固定的IP地址加一条iptables规则

**Comment by xw-l** [comment]
当我设置防火墙规则后，设备列表会掉线，地址簿没有问题，但其他客户端无法登陆，因为登陆是访问21114端口，是我形容不够详细，不好意思，至于设备信息，感觉也是客户端主动提供给21114端口的api，好像也没什么影响

**Comment by lejianwen** [comment]
pc客户端是会和21114通信的，如果你填了api server，上传设备信息，获取地址簿、标签等等
你是想admin后台只允许特定的IP访问吗？

**Comment by lejianwen** [comment]
这种情况的话，你可以在前面放个nginx反代，通过nginx来限制IP的访问，比较方便

**Comment by xw-l** [comment]
好，俺试试，感谢大佬

**Comment by lejianwen** [comment]
客气了  多谢支持
