### ISSUE TITLE
web admin中禁用webclient

### ISSUE THREAD

**Issue by redjumper** [lejianwen/rustdesk-api#9]
首先感谢作者这个项目。
我不需要webclient，能否提供个环境变量开关，在api-server后台禁用webclient，并且不路由到webclient

**Comment by lejianwen** [comment]
可以的 我后面加上，你可以先直接删除resurces/web目录，这样webclient将不可用

**Comment by lejianwen** [comment]
现在有RUSTDESK_API_APP_WEB_CLIENT控制web client ，1启用，0 禁用，默认启用

**Comment by redjumper** [comment]
感谢作者，路由已不可达。有个小bug。地址簿里面还有webclient按钮，问题不大

**Comment by lejianwen** [comment]
确实，忘记了
我更新下

**Comment by redjumper** [comment]
更新后地址簿里没有任何设备了

**Comment by lejianwen** [comment]
我的，忘记import了

**Comment by lejianwen** [comment]
更新修复了

**Comment by redjumper** [comment]
现在完美了

2024年10月14日 12:32:37 乐 ***@***.***>:
