### ISSUE TITLE
是否可以实现Pro版中的多中继服务器功能

### ISSUE THREAD

**Issue by Gavin-TnT** [lejianwen/rustdesk-api#91]
类似于这样的:https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/relay/

**Comment by wy414012** [comment]
@Gavin-TnT 按照这里的环境变量，使用修正过的开源版server，多中继，多id都是可以正常工作的https://github.com/wy414012/rustdesk-server

**Comment by Gavin-TnT** [comment]
> @Gavin-TnT 按照这里的环境变量，使用修正过的开源版server，多中继，多id都是可以正常工作的https://github.com/wy414012/rustdesk-server

哇 感谢大佬 我研究研究

**Comment by lejianwen** [comment]
多中继服务器似乎官方的是支持的，但geo功能需要pro版本才支持，这个我也没了解过，api这边应该是做不到此功能
ε=ε=ε=┏(゜ロ゜;)┛

你可以试试大佬们的server端

**Comment by luguoyixiazi** [comment]
> [@Gavin-TnT](https://github.com/Gavin-TnT) 按照这里的环境变量，使用修正过的开源版server，多中继，多id都是可以正常工作的https://github.com/wy414012/rustdesk-server

按你的环境变量配置，但是看日志输出的RELAY_SERVERS永远是空列表，难道不是只在server的容器的env配置RELAY_SERVERS=serverip:21117,server2ip:21117和配置RENDZVOUS_SERVERS就行了吗？
实际测试感觉也是单纯看哪个最快能连就走哪个了
emmm……总感觉这种东西的做法有点不太恰当，或许应该加一个网速测试吧，不然延迟最短的，但带宽挤占，实际卡顿之下可能还不如延迟稍微大一点点但是带宽空闲的机子
